name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get remove -y lcov || true
        sudo apt-get install -y libperlio-gzip-perl libjson-pp-perl libcapture-tiny-perl libdatetime-perl
        wget https://github.com/linux-test-project/lcov/releases/download/v2.1/lcov-2.1.tar.gz
        tar -xzf lcov-2.1.tar.gz
        cd lcov-2.1
        sudo make install

    - name: Install Nim
      run: |
        export CHOOSENIM_CHOOSE_VERSION="2.2.10"
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y

    - name: Run Tests and Generate Coverage
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble coverage

    - name: Generate HTML Documentation
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble docs

    - name: Generate Coverage Report
      run: |
        ./code_coverage.sh

    - name: Check Generated Documentation
      run: |
        git diff --exit-code docs/
        if [ -n "$(git status --porcelain docs/)" ]; then
          git status --porcelain docs/
          exit 1
        fi

    - name: Commit Badge and Documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git diff-index --quiet HEAD || git commit -m "Update docs and coverage badge [skip ci]" -a
        git push
